name: Check and update xLights release
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Update formula
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.1.0
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Cache .bundle
        uses: actions/cache@preview
        with:
          path: .bundle
          key: ${{ runner.os }}-ruby-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-
      - run: |
          gem install bundler --no-document
          bundle install --path .bundle
      - name: Perform formula update
        run: |
          ruby util/update_formula.rb
          git push --follow-tags
